name: Github Action Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build:css
      - run: npm run build:blocks
      - run: npm run package
      - name: Deploy
        env:
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.SSH_PORT }}
          USER: ${{ secrets.USER }}
          DEST: ${{ secrets.THEME_PATH }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          rsync -az --delete \
            -e "ssh -p ${{ PORT }} -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" \
            release/ \
            $USER@$HOST:$DEST